### ISSUE TITLE
strange failure

### ISSUE THREAD

**Issue by f4eru** [chintal/fpv-gcc#2]
Hello, I get this error:
```

fpvgcc --ssec build/Firmware.map_error 
Traceback (most recent call last):
  File "/usr/local/bin/fpvgcc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fpvgcc/cli.py", line 215, in main
    state_machine = process_map_file(args.mapfile)
  File "/usr/local/lib/python2.7/dist-packages/fpvgcc/fpv.py", line 534, in process_map_file
    process_linkermap_line(line, sm)
  File "/usr/local/lib/python2.7/dist-packages/fpvgcc/fpv.py", line 497, in process_linkermap_line
    process_linkermap_symbol_line(l, sm)
  File "/usr/local/lib/python2.7/dist-packages/fpvgcc/fpv.py", line 344, in process_linkermap_symbol_line
    name = linkermap_name_process(name, sm)
  File "/usr/local/lib/python2.7/dist-packages/fpvgcc/fpv.py", line 264, in linkermap_name_process
    if not name.startswith(sm.linkermap_section.gident):
AttributeError: 'NoneType' object has no attribute 'gident'

```

Attached zipped file is simplified down to the error source.
[Firmware.zip](https://github.com/chintal/fpv-gcc/files/2995992/Firmware.zip)
Removing the following line makes it succeed: 

` .ARM.exidx     0x0000000008006e38        0x8 /home/dev/opt/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v6-m/libgcc.a(_divdi3.o)`

**Comment by chintal** [comment]
@f4eru Thanks for the report. I'll take a look at it and see where it's coming from.

**Comment by chintal** [comment]
@f4eru Please try the latest version (v0.8.2 or git HEAD as of this writing). I think it works around the more immediate problem. Unfortunately, it will take a little more digging to reliably solve the issue. I will need a more complete example map file to figure out what is going on with it.

**Comment by f4eru** [comment]
Hello,
Both 0.8.2 and 0.8.3 work on the full original file for me, thanks !

**Comment by f4eru** [comment]
In attachement the original map file.
0.8.3 gives a garbled output ith this one, seemingly lacking some end of lines..
[map.zip](https://github.com/chintal/fpv-gcc/files/3037805/map.zip)

**Comment by chintal** [comment]
@f4eru The --ssec output can get pretty garbled very easily. The table that it results in is simply far too large (wide), and each line overflows (wraps) into a number of lines with even a slightly non-trivial program. It exists because at some point in the distant future, when I have the time, I would want to put in a web or desktop UI which would be able to handle the details, with baobab or filelight as a model of what I would want it to look and feel like.

The per-section split of memory utilization, in my experience, is rarely useful. I would recommend using the other more compact and useful outputs, and I suspect you will get the information you need (as opposed to what you want).

However, if you wish, you can play around with print_sectioned_fp() of cli.py ( https://github.com/chintal/fpv-gcc/blob/d6e678611cb2407390fb7d69ef1573788287c263/fpvgcc/cli.py#L124 ). I'll be more than happy to accept a pull request. 

There is still a boundary condition which the original issue seems to hit which I'm concerned about and could cause some miscounting. This does not seem to be an issue in the map files generated for AVR and MSP devices. I will keep an eye on it and make corrections as and when specific inaccuracies present themselves.

In the meanwhile, I'm closing the issue. Feel free to open a new one if you need more and/or assistance, or a PR if you have a more usable --ssec output you'd like to discuss.
